package datavision.utils.settings;

public enum AlgorithmConfigurationDialogSettings {

    MAX_ITERATION,
    UPDATE_INTERVAL,
    CONTINUOUS_RUN,
    ALGORITHM_CONFIGURATION_DIALOG_OK,
    INVALID_CONFIGURATION_TITLE,
    INVALID_CONFIGURATION_MESSAGE,
    MUST_BE_INTEGER_FORMAT_STRING,
    MUST_BE_NON_NEGATIVE_FORMAT_STRING,
    MUST_BE_NON_ZERO_FORMAT_STRING,
    MUST_BE_WITHIN_RANGE_FORMAT_STRING

}
