package datavision.utils.settings;

public enum AlgorithmAPISettings {

    CLASS_EXTENSION,
    ESCAPED_CLASS_EXTENSION,

    ALGORITHM_CLASS_FORMAT_STRING,
    ALGORITHM_ADAPTER_CLASS_FORMAT_STRING,
    ALGORITHM_CONFIG_CLASS_FORMAT_STRING,

    ALGORITHM_DIRECTORY,
    ALGORITHM_ADAPTER_DIRECTORY,
    ALGORITHM_CONFIGURATION_DIALOG_DIRECTORY,

    ALGORITHM_ADAPTER_SUFFIX,
    ALGORITHM_CONFIG_SUFFIX,

    ALGORITHM_ADAPTER_PATH,
    ALGORITHM_PATH,
    ALGORITHM_CONFIG_PATH

}
