package datavision.utils.settings;

public enum AppActionSettings {

    ALGORITHM_IS_STILL_RUNNING_TITLE,
    ALGORITHM_IS_STILL_RUNNING_STOP_ALGORITHM_MESSAGE,
    ALGORITHM_IS_STILL_RUNNING_QUIT_APPLICATION_MESSAGE

}
